# Generated by Django 5.2.12 on 2026-03-05 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('descricao', models.TextField(blank=True)),
                ('tecnologias', models.CharField(blank=True, max_length=200)),
                ('link_github', models.URLField(blank=True)),
                ('link_demo', models.URLField(blank=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='projetos/')),
                ('destaque', models.BooleanField(default=False)),
                ('criado_em', models.DateField(blank=True, null=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['ordem', '-destaque', '-id'],
            },
        ),
    ]
