# Generated by Django 5.2.12 on 2026-03-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='tem_download',
            field=models.BooleanField(default=False),
        ),
    ]
