# Generated by Django 5.2.12 on 2026-03-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_projeto_tem_download'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='imagem',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Imagem'),
            preserve_default=False,
        ),
    ]
