# Generated by Django 5.2.12 on 2026-03-19 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_projeto_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='video_demo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
