# Generated by Django 5.2.12 on 2026-05-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_projeto_video_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='tempo_desenvolvimento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
